name: CI Workflow

on:
  push:
    branches:
      - master  # Changed to 'smaster'
  pull_request:
    branches:
      - master  # Changed to 'smaster'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the appropriate version as per your setup

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Run Playwright tests
      - name: Run Playwright tests
        run: |
          npx playwright install
          npx playwright test

      # Run Vitest tests
      - name: Run Vitest tests
        run: |
          npx vitest run

      # Build the application (optional, if needed)
      - name: Build the application
        run: |
          npm run build

      # Run lint (optional, if needed)
      - name: Run lint
        run: |
          npm run lint
