name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'  # Use the correct Node.js version

      - name: Install dependencies
        run: |
          npm ci  # Prefer npm ci over npm install for clean installs in CI
          npm install vitest --save-dev  # Explicitly install vitest
          npm install typescript --save-dev  # Ensure TypeScript is installed
          npm install playwright  # Ensure playwright is installed

  run_tests:
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      - name: Run Vitest tests
        run: |
          npx vitest run  # Run vitest tests

      - name: Run Playwright tests
        run: |
          npx playwright test  # Run Playwright tests

  build_check:
    needs: run_tests
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      - name: Build Next.js app
        run: |
          npm run build  # Make sure the build runs correctly

  generate_coverage_report:
    needs: build_check
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      - name: Generate Coverage Report
        run: |
          npx vitest run --coverage  # Run tests with coverage report
