name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install


       # Run Vitest tests
      - name: Run Vitest tests
        run: |
         npx vitest run

      # Start Next.js server in the foreground and wait for it to be ready
      - name: Start Next.js server and run Playwright tests
        run: |
          npx playwright install
          npx playwright test

      # Build the application (optional)
      - name: Build the application
        run: |
          npm run build

      # Run lint (optional)
      - name: Run lint
        run: |
          npm run lint
