name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use Node.js version compatible with Next.js

      - name: Install dependencies
        run: |
          npm install
          npm install playwright

  run_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run Vitest unit tests
        run: |
          npx vitest 

      - name: Run Playwright tests
        run: |
          npx playwright test  # Run Playwright tests

  build_check:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: |
          npm run dev  # Build the Next.js app to verify it builds correctly

  coverage_report:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Upload coverage results
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/coverage-final.json  # Path to the coverage report generated by Vitest

