name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Run Vitest tests
      - name: Run Vitest tests
        run: |
          npx vitest run

      # Install Playwright and cache its browsers
      - name: Install Playwright and cache browsers
        run: |
          npx playwright install

      # Start Next.js server in the background
      - name: Start Next.js server
        run: |
          npm run dev & # Runs the Next.js server in the background
          # Wait for the server to be ready (check if port 3000 is available)
          npx wait-on http://localhost:3000

      # Run Playwright tests
      - name: Run Playwright tests
        run: |
          npx playwright test

      # Build the application (optional)
      - name: Build the application
        run: |
          npm run build

      # Run lint (optional)
      - name: Run lint
        run: |
          npm run lint
